import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}


export default function RootLayout({ children, params }) {
      const { slug } = params;
      console.log(slug)
  return (
    <html lang="tr">
      <body className={`${montserrat.className} md:!overflow-y-scroll overflow-x-hidden smooth-scrool 	`}>
        <Header />
        {children}       
      </body>
    </html>
  );
}
